apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadiya-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 065882759854.dkr.ecr.us-east-1.amazonaws.com/hadiya1:latest
        ports:
        - containerPort: 3000
~                                                                                                                                                                                                          
~                                  
